import { Typography } from "@mui/material";
import React from "react";
import WrapperComponent from "../../components/WrapperComponent";

const PrivacyPolicies = () => {
  return (
    <WrapperComponent isHeader={true}>
<div>
      <img
        src={"././plastocurrentlogo.png"}
        style={{ height: "auto", width: "16%", marginLeft: "44%" }}
      />
      <br />
      <br />
      <Typography fontSize="20px" fontWeight="bolded">
        <b>PRIVACY POLICY</b>
      </Typography>
      <br />
      <Typography>Effective date: 2022-07-31</Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Introduction</b>
      </Typography>
      <br />
      <Typography>
        Welcome to <b>allxsolutions llp.</b>
      </Typography>
      <br />
      <Typography>
        <b>allxsolutions llp</b> (“us”, “we”, or “our”) operates{" "}
        <b>www.plastodeal.com</b> (hereinafter referred to as <b>“Service”</b>).
      </Typography>
      <br />
      <Typography>
        Our Privacy Policy governs your visit to <b>www.plastodeal.com</b>, and
        explains how we collect, safeguard and disclose information that results
        from your use of our Service.
      </Typography>
      <br />
      <Typography>
        Our Terms and Conditions<b> (“Terms”)</b> govern all use of our Service
        and together with the Privacy Policy constitutes your agreement with us
        <b> (“agreement”)</b>.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Definitions</b>
      </Typography>
      <br />
      <Typography>
        <b> SERVICE</b> means the www.plastodeal.com website operated by
        allxsolutions llp.
      </Typography>
      <br />
      <Typography>
        <b>PERSONAL DATA</b> means data about a living individual who can be
        identified from those data (or from those and other information either
        in our possession or likely to come into our possession).
      </Typography>
      <br />
      <Typography>
        <b>USAGE DATA</b> is data collected automatically either generated by
        the use of Service or from Service infrastructure itself (for example,
        the duration of a page visit).
      </Typography>
      <br />
      <Typography>
        <b>COOKIES</b> are small files stored on your device (computer or mobile
        device).
      </Typography>
      <br />
      <Typography>
        <b>DATA CONTROLLER </b> means a natural or legal person who (either
        alone or jointly or in common with other persons) determines the
        purposes for which and the manner in which any personal data are, or are
        to be, processed. For the purpose of this Privacy Policy, we are a Data
        Controller of your data.
      </Typography>
      <br />
      <Typography>
        <b>DATA PROCESSORS (OR SERVICE PROVIDERS)</b> means any natural or legal
        person who processes the data on behalf of the Data Controller. We may
        use the services of various Service Providers in order to process your
        data more effectively.
      </Typography>
      <br />
      <Typography>
        <b> DATA SUBJECT</b> is any living individual who is the subject of
        Personal Data.
      </Typography>
      <br />
      <Typography>
        <b>THE USER</b> is the individual using our Service. The User
        corresponds to the Data Subject, who is the subject of Personal Data.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Information Collection and Use</b>
      </Typography>
      <br />
      <Typography>
        We collect several different types of information for various purposes
        to provide and improve our Service to you.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Types of Data Collected</b>
      </Typography>
      <br />
      <Typography>
        <b>Personal Data</b>
      </Typography>
      <br />
      <Typography>
        While using our Service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you<b> (“Personal Data”)</b>. Personally identifiable
        information may include, but is not limited to:
      </Typography>
      <br />
      <Typography>
        0<b>.</b>1<b>.</b> Email address
      </Typography>
      <br />
      <Typography>
        0<b>.</b>2<b>.</b> First name and last name
      </Typography>
      <br />
      <Typography>
        0<b>.</b>3<b>.</b> Phone number
      </Typography>
      <br />
      <Typography>
        0<b>.</b>4<b>.</b> Address, Country, State, Province, ZIP/Postal code,
        City
      </Typography>
      <br />
      <Typography>
        0<b>.</b>5<b>.</b> Cookies and Usage Data
      </Typography>
      <br />
      <Typography>
        <b> Usage Data</b>
      </Typography>
      <br />
      <Typography>
        We may also collect information that your browser sends whenever you
        visit our Service or when you access Service by or through any device
        <b>(“Usage Data”)</b>.
      </Typography>
      <br />
      <Typography>
        This Usage Data may include information such as your computer’s Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that you visit, the time and date of your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </Typography>
      <br />
      <Typography>
        When you access Service with a device, this Usage Data may include
        information such as the type of device you use, your device unique ID,
        the IP address of your device, your device operating system, the type of
        Internet browser you use, unique device identifiers and other diagnostic
        data.
      </Typography>
      <br />
      <Typography>
        <b> Location Data</b>
      </Typography>
      <br />
      <Typography>
        We may use and store information about your location if you give us
        permission to do so<b> (“Location Data”)</b>. We use this data to
        provide features of our Service, to improve and customize our Service.
      </Typography>
      <br />
      <Typography>
        You can enable or disable location services when you use our Service at
        any time by way of your device settings.
      </Typography>
      <br />
      <Typography>
        <b>Tracking Cookies Data</b>
      </Typography>
      <br />
      <Typography>
        We use cookies and similar tracking technologies to track the activity
        on our Service and we hold certain information.
      </Typography>
      <br />
      <Typography>
        Cookies are files with a small amount of data which may include an
        anonymous unique identifier. Cookies are sent to your browser from a
        website and stored on your device. Other tracking technologies are also
        used such as beacons, tags and scripts to collect and track information
        and to improve and analyze our Service.
      </Typography>
      <br />
      <Typography>
        You can instruct your browser to refuse all cookies or to indicate when
        a cookie is being sent. However, if you do not accept cookies, you may
        not be able to use some portions of our Service.
      </Typography>
      <br />
      <Typography>Examples of Cookies we use:</Typography>
      <br />
      <Typography>
        0<b>.</b>1<b>.</b> <b>Session Cookies:</b> We use Session Cookies to
        operate our Service.
      </Typography>
      <br />
      <Typography>
        0<b>.</b>2<b>.</b> <b>Preference Cookies:</b> We use Preference Cookies
        to remember your preferences and various settings.
      </Typography>
      <br />
      <Typography>
        0<b>.</b>3<b>.</b> <b>Security Cookies:</b> We use Security Cookies for
        security purposes.
      </Typography>
      <br />
      <Typography>
        0<b>.</b>4<b>.</b> <b>Advertising Cookies:</b> Advertising Cookies are
        used to serve you with advertisements that may be relevant to you and
        your interests.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Use of Data</b>
      </Typography>
      <br />
      <Typography>
        allxsolutions llp uses the collected data for various purposes:
      </Typography>
      <br />
      <Typography>
        0<b>.</b>1<b>.</b> to provide and maintain our Service;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>2<b>.</b> to notify you about changes to our Service;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>3<b>.</b> to allow you to participate in interactive features
        of our Service when you choose to do so;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>4<b>.</b> to provide customer support;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>5<b>.</b> to gather analysis or valuable information so that we
        can improve our Service; to provide and maintain our Service;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>6<b>.</b> to monitor the usage of our Service;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>7<b>.</b> to detect, prevent and address technical issues;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>8<b>.</b> to fulfil any other purpose for which you provide it;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>9<b>.</b> to carry out our obligations and enforce our rights
        arising from any contracts entered into between you and us, including
        for billing and collection;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>10<b>.</b> to provide you with notices about your account
        and/or subscription, including expiration and renewal notices,
        email-instructions, etc.;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>11<b>.</b> to provide you with news, special offers and general
        information about other goods, services and events which we offer that
        are similar to those that you have already purchased or enquired about
        unless you have opted not to receive such information;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>12<b>.</b> in any other way we may describe when you provide
        the information;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>13<b>.</b> for any other purpose with your consent.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Retention of Data</b>
      </Typography>
      <br />
      <Typography>
        We will retain your Personal Data only for as long as is necessary for
        the purposes set out in this Privacy Policy. We will retain and use your
        Personal Data to the extent necessary to comply with our legal
        obligations (for example, if we are required to retain your data to
        comply with applicable laws), resolve disputes, and enforce our legal
        agreements and policies.
      </Typography>
      <br />
      <Typography>
        We will also retain Usage Data for internal analysis purposes. Usage
        Data is generally retained for a shorter period, except when this data
        is used to strengthen the security or to improve the functionality of
        our Service, or we are legally obligated to retain this data for longer
        time periods.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Transfer of Data</b>
      </Typography>
      <br />
      <Typography>
        Your information, including Personal Data, may be transferred to – and
        maintained on – computers located outside of your state, province,
        country or other governmental jurisdiction where the data protection
        laws may differ from those of your jurisdiction.
      </Typography>
      <br />
      <Typography>
        If you are located outside india and choose to provide information to
        us, please note that we transfer the data, including Personal Data, to
        india and process it there.
      </Typography>
      <br />
      <Typography>
        Your consent to this Privacy Policy followed by your submission of such
        information represents your agreement to that transfer.
      </Typography>
      <br />
      <Typography>
        allxsolutions llp will take all the steps reasonably necessary to ensure
        that your data is treated securely and in accordance with this Privacy
        Policy and no transfer of your Personal Data will take place to an
        organisation or a country unless there are adequate controls in place
        including the security of your data and other personal information.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Disclosure of Data</b>
      </Typography>
      <br />
      <Typography>
        We may disclose personal information that we collect, or you provide:
      </Typography>
      <br />
      <Typography>
        0<b>.</b>1<b>.</b> <b>Disclosure for Law Enforcement.</b>
      </Typography>
      <br />
      <Typography>
        Under certain circumstances, we may be required to disclose your
        Personal Data if required to do so by law or in response to valid
        requests by public authorities.
      </Typography>
      <br />
      <Typography>
        0<b>.</b>2<b>.</b> <b> Business Transaction.</b>
      </Typography>
      <br />
      <Typography>
        If we or our subsidiaries are involved in a merger, acquisition or asset
        sale, your Personal Data may be transferred.
      </Typography>
      <br />
      <Typography>
        0<b>.</b>3<b>.</b>
        <b> Other cases. We may disclose your information also:</b>
      </Typography>
      <br />
      <Typography>
        0<b>.</b>3<b>.</b>1 to our subsidiaries and affiliates;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>3<b>.</b>2 to contractors, service providers, and other third
        parties we use to support our business;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>3<b>.</b>3 to fulfill the purpose for which you provide it;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>3<b>.</b>4 for the purpose of including your company’s logo on
        our website;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>3<b>.</b>5 for any other purpose disclosed by us when you
        provide the information;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>3<b>.</b>6 with your consent in any other cases;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>3<b>.</b>7 if we believe disclosure is necessary or appropriate
        to protect the rights, property, or safety of the Company, our
        customers, or others.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Security of Data</b>
      </Typography>
      <br />
      <Typography>
        The security of your data is important to us but remember that no method
        of transmission over the Internet or method of electronic storage is
        100% secure. While we strive to use commercially acceptable means to
        protect your Personal Data, we cannot guarantee its absolute security.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>
          Your Data Protection Rights Under General Data Protection Regulation
          (GDPR)
        </b>
      </Typography>
      <br />
      <Typography>
        We aim to take reasonable steps to allow you to correct, amend, delete,
        or limit the use of your Personal Data.
      </Typography>
      <br />
      <Typography>
        If you wish to be informed what Personal Data we hold about you and if
        you want it to be removed from our systems, please email us at{" "}
        <b>plastodeal@gmail.com.</b>
      </Typography>
      <br />
      <Typography>
        In certain circumstances, you have the following data protection rights:
      </Typography>
      <br />
      <Typography>
        0<b>.</b>1 the right to access, update or to delete the information we
        have on you;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>2 the right of rectification. You have the right to have your
        information rectified if that information is inaccurate or incomplete;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>3 the right to object. You have the right to object to our
        processing of your Personal Data;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>4 the right of restriction. You have the right to request that
        we restrict the processing of your personal information;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>5 the right to data portability. You have the right to be
        provided with a copy of your Personal Data in a structured,
        machine-readable and commonly used format;
      </Typography>
      <br />
      <Typography>
        0<b>.</b>6 the right to withdraw consent. You also have the right to
        withdraw your consent at any time where we rely on your consent to
        process your personal information;
      </Typography>
      <br />
      <Typography>
        Please note that we may ask you to verify your identity before
        responding to such requests. Please note, we may not able to provide
        Service without some necessary data.
      </Typography>
      <br />
      <Typography>
        You have the right to complain to a Data Protection Authority about our
        collection and use of your Personal Data. For more information, please
        contact your local data protection authority in the European Economic
        Area (EEA).
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        To exercise your data protection rights, you can make certain requests
        and ask us:
      </Typography>
      <br />
      <Typography>
        <b>
          0.1. What personal information we have about you. If you make this
          request, we will return to you:
        </b>
      </Typography>
      <br />
      <Typography>
        0<b>.</b>0<b>.</b>1 The categories of personal information we have
        collected about you.
      </Typography>
      <br />
      <Typography>
        0<b>.</b>0<b>.</b>2 The categories of sources from which we collect your
        personal information.
      </Typography>
      <br />
      <Typography>
        0<b>.</b>0<b>.</b>3 The business or commercial purpose for collecting or
        selling your personal information.
      </Typography>
      <br />
      <Typography>
        0<b>.</b>0<b>.</b>4 The categories of third parties with whom we share
        personal information.
      </Typography>
      <br />
      <Typography>
        0<b>.</b>0<b>.</b>5 The specific pieces of personal information we have
        collected about you.
      </Typography>
      <br />
      <Typography>
        0<b>.</b>0<b>.</b>6 A list of categories of personal information that we
        have sold, along with the category of any other company we sold it to.
        If we have not sold your personal information, we will inform you of
        that fact.
      </Typography>
      <br />
      <Typography>
        0<b>.</b>0<b>.</b>7 A list of categories of personal information that we
        have disclosed for a business purpose, along with the category of any
        other company we shared it with.
      </Typography>
      <br />
      <Typography>
        <b>
          0.2. To delete your personal information. If you make this request, we
          will delete the personal information we hold about you as of the date
          of your request from our records and direct any service providers to
          do the same. In some cases, deletion may be accomplished through
          de-identification of the information. If you choose to delete your
          personal information, you may not be able to use certain functions
          that require your personal information to operate.
        </b>
      </Typography>
      <br />
      <Typography>
        Please note, if you ask us to delete or stop selling your data, it may
        impact your experience with us, and you may not be able to participate
        in certain programs or membership services which require the usage of
        your personal information to function. But in no circumstances, we will
        discriminate against you for exercising your rights.
      </Typography>
      <br />
      <Typography>
        To exercise your data protection rights described above, please send
        your request(s) by email: <b>plastodeal@gmail.com</b>.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Service Providers</b>
      </Typography>
      <br />
      <Typography>
        We may employ third party companies and individuals to facilitate our
        Service <b>(“Service Providers”)</b>, provide Service on our behalf,
        perform Service-related services or assist us in analysing how our
        Service is used.
      </Typography>
      <br />
      <Typography>
        These third parties have access to your Personal Data only to perform
        these tasks on our behalf and are obligated not to disclose or use it
        for any other purpose.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Analytics</b>
      </Typography>
      <br />
      <Typography>
        We may use third-party Service Providers to monitor and analyze the use
        of our Service.
      </Typography>
    
      <br/>
      <Typography sx={{ marginLeft: "2%" }}>
        <b>CI/CD tools</b>
      </Typography>
      <br />
      <Typography>
        We may use third-party Service Providers to automate the development
        process of our Service.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Advertising</b>
      </Typography>
      <br />
      <Typography>
        We may use third-party Service Providers to show advertisements to you
        to help support and maintain our Service.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Behavioral Remarketing</b>
      </Typography>
      <br />
      <Typography>
      We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Payments</b>
      </Typography>
      <br />
      <Typography>
      We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).
      </Typography>
      <br />
      <Typography>
      We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Links to Other Sites</b>
      </Typography>
      <br />
      <Typography>
      We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).
      </Typography>
      <br />
      <Typography>
      We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Changes to This Privacy Policy</b>
      </Typography>
      <br />
      <Typography>
      We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
      </Typography>
      <br />
      <Typography>
      We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.
      </Typography>
      <br />
      <Typography>
      You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
      </Typography>
      <br />
      <Typography sx={{ marginLeft: "2%" }}>
        <b>Contact Us</b>
      </Typography>
      <br />
      <Typography>
      If you have any questions about this Privacy Policy, please contact us by email: <b>plastodeal@gmail.com</b>.
      </Typography>
      <br />
      
    </div>
    </WrapperComponent>
    
  );
};

export default PrivacyPolicies;
